name: Rubie7
favicon: null
layout_spectrum: 0.99957
typography_spectrum: 0.13391
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#09080d'
    - '#bebebe'
    - '#56534e'
    - '#9e9fa1'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.6419505728408694
purpose: []
